### ISSUE TITLE
IAR internal error?

### ISSUE THREAD

**Issue by czdpd** [hathach/tinyusb#570] opened 2020-12-17 17:21 UTC
Hi,
I try to bring tinyUsb to my project using IAR EWARM(8.5). I added the source files, copied tusb_config.h and usb_descriptor.c from one of the examples. I expect to get a lot compiler errors and I'll work from there. But instead I got IAR internal errors like this:

Tool Internal Error: 
Internal Error: [Front end]: assertion failed at: "layout.c", line 2909 in set_field_size_and_offset 

I wonder if I missed anything, like compiler specific configuration etc? It appears this only happens to these files: tusb.c, usbd.c, usbd_control.c, msc_device.c.

Any idea? Thanks!

**Comment by HiFiPhile** [comment] 2020-12-17 21:12
Hi,

That's quite strange.... Which class driver are you using ?

**Comment by czdpd** [comment] 2020-12-18 05:44
I added cdc, hid, msc sources to my project. The tusb_config.h has CFG_TUD_CDC and CFG_TUD_MSC set to 1 so I guess they're enabled.

**Comment by HiFiPhile** [comment] 2020-12-18 10:44
Could you upload your project ? I can't reproduce on 8.50.6 and 8.50.9

**Comment by czdpd** [comment] 2020-12-18 22:34
Here's my test project. I used ST's example project for the Nucleo STM32L452 board. 
Tinyusb source should be under the directory 'tinyusb'.
IAR project file is at: test_proj\STM32Cube_FW_L4_V1.13.0\Projects\NUCLEO-L452RE\Templates_LL\EWARM

[test_proj.zip](https://github.com/hathach/tinyusb/files/5718370/test_proj.zip)

**Comment by HiFiPhile** [comment] 2020-12-20 21:57
It should be fixed by #573

**Comment by hathach** [comment] 2020-12-23 05:54
closed by #573

**Closed by hathach** 2020-12-23 05:54 UTC
